In [1]:
import numpy as np
import pandas as pd

In [2]:
sad = pd.read_csv("sad.csv")
happy = pd.read_csv("happy.csv")
angry = pd.read_csv("angry.csv")

In [3]:
print("Happy:", happy.shape)
print("Sad:", sad.shape)
print("Angry:", angry.shape)

Happy: (708, 2)
Sad: (635, 2)
Angry: (696, 2)

In [4]:
happy.head(2)

                                             content sentiment
0  Wants to know how the hell I can remember word...     happy
1  Love is a long sweet dream & marriage is an al...     happy

In [5]:
sad.head(2)

                                             content sentiment
0  Never hurt people who love you a lot, because ...       sad
1  Don’t expect me to tell you what you did wrong...       sad

In [6]:
angry.head(2)

                                             content sentiment
0  Sometimes I’m not angry, I’m hurt and there’s ...     angry
1                     Not available for busy people☺     angry

In [8]:
happy = happy.drop_duplicates(subset = "content", keep = "first")
sad = sad.drop_duplicates(subset = "content", keep = "first")
angry = angry.drop_duplicates(subset = "content", keep = "first")

In [9]:
frames = [happy, sad, angry]
df = pd.concat(frames)

In [10]:
df.head(3)

                                             content sentiment
0  Wants to know how the hell I can remember word...     happy
1  Love is a long sweet dream & marriage is an al...     happy
2  The world could be amazing when you are slight...     happy

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1592 entries, 0 to 694
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   content    1592 non-null   object
 1   sentiment  1592 non-null   object
dtypes: object(2)
memory usage: 37.3+ KB

In [12]:
df = df.drop_duplicates(subset = "content", keep = "first")

In [13]:
df["sentiment"].value_counts()

sentiment
happy    704
angry    494
sad      388
Name: count, dtype: int64

In [15]:
df.replace({"sentiment": {"happy": 1, "angry": 0, "sad": 2}}, inplace=True)

import pandas as pd
pd.set_option('future.no_silent_downcasting', True)

In [16]:
df['sentiment'].value_counts()

sentiment
1    704
0    494
2    388
Name: count, dtype: int64

In [17]:
import re
def html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, "", text)
df["content"] = df["content"].apply(html)

In [18]:
def lower(text):
    return text.lower()
df["content"] = df["content"].apply(lower)

In [19]:
def special(text):
        x=''
        for i in text:
            if i.isalnum():
                x=x+i
            else:
                x=x+' '
        return x
df['content']=df['content'].apply(special)

In [20]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
import nltk
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HARGUN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [21]:
def r_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y
df['content']=df['content'].apply(r_stopwords)

In [22]:
def join_back(list_input):
    return " ".join(list_input)
df['content']=df['content'].apply(join_back)

In [23]:
ps= PorterStemmer()
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z
df['content']=df['content'].apply(stem_words)

In [25]:
def joinback2(list_input):
    return "".join(list_input)
df['content']=df['content'].apply(joinback2)

In [26]:
df

                                               content  sentiment
0    wants know hell remember words songs years ago...          1
1           love long sweet dream marriage alarm clock          1
2                 world could amazing slightly strange          1
3         secret talent getting tired without anything          1
4     khatarnaak whatsapp status ever talk wife around          1
..                                                 ...        ...
681  embarrassment anger biggest humiliation person...          0
685  strong man good wrestler strong man one contro...          0
687                          man big things make angry          0
693                    singing angry know punches face          0
694            telling someone calm makes much angrier          0

[1586 rows x 2 columns]

In [27]:
X = df["content"]

In [28]:
y=df.iloc[:,-1].values

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.3)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1500)

In [31]:
X_train = cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [32]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [33]:
model.fit(X_train,y_train)

MultinomialNB()

In [34]:
y_pred2=model.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score
print("Multinomial",accuracy_score(y_test,y_pred2))

Multinomial 0.7247899159663865

In [36]:
test="i am sad & depressed too"

In [37]:
test = np.array([test])
test = cv.transform(test)

In [38]:
model.predict(test)

array([2])